name: Create Github release

on:
  workflow_call:

jobs:
  create-release:
    name: Create a Github release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
